INSERT INTO Ingredients( name )
    VALUES
    ( 'onion' ),
    ( 'pepper' ),
    ( 'minced meat' ),
    ( 'merguez' ),
    ( 'egg' ),
    ( 'bacon' ),
    ( 'tomato' ),
    ( 'pineapple' ),
    ( 'cheddar' ),
    ( 'olive' ),
    ( 'goat cheese' ),
    ( 'honey' ),
    ( 'chorizo' ),
    ( 'ham' ),
    ( 'mozarella' ),
    ( 'chicken' ),
    ( 'salmon' ),
    ( 'tuna' ),
    ( 'mushroom' ),
    ( 'chilli pepper' ),
    ( 'anchovy' ),
    ( 'spinach' ),
    ( 'parmesan cheese' ),
    ( 'reblochon' ),
    ( 'fresh cream' ),
    ( 'basil' ),
    ( 'raclette' ),
    ( 'gruyere' ),
    ( 'boursin' ),
    ( 'corn' );
